# Generated by Django 5.2.6 on 2025-09-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='price_delta',
        ),
    ]
